In [1]:
import pandas as pd
import numpy as np
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.model_selection import cross_val_score, train_test_split
from sklearn.metrics import confusion_matrix
import dask.dataframe as dd
from dask_ml.preprocessing import OneHotEncoder, DummyEncoder, Categorizer, LabelEncoder, StandardScaler
pd.set_option('display.max_rows', 200)

In [2]:
approved_data = dd.read_csv('../data/approved1.csv')

In [3]:
approved_data.dtypes

id                        int64
addr_state               object
annual_inc              float64
application_type         object
disbursement_method      object
dti                     float64
earliest_cr_line         object
emp_length               object
emp_title                object
fico_range_high         float64
fico_range_low          float64
grade                    object
home_ownership           object
initial_list_status      object
installment             float64
int_rate                float64
issue_d                  object
loan_amnt               float64
open_acc                float64
pub_rec                 float64
pub_rec_bankruptcies    float64
purpose                  object
sub_grade                object
term                     object
verification_status      object
zip_code                 object
loan_status              object
dtype: object

In [4]:
# number of missing in id
# print('Number of missing in addr_state: ', approved_data.addr_state.isna().sum().compute())
# print('Number of missing in annual_inc: ', approved_data.annual_inc.isna().sum().compute())
# print('Number of missing in disbursement_method: ', approved_data.disbursement_method.isna().sum().compute())
# print('Number of missing in dti: ', approved_data.dti.isna().sum().compute())
# print('Number of missing in earliest_cr_line: ', approved_data.earliest_cr_line.isna().sum().compute())
# print('Number of missing in emp_length: ', approved_data.emp_length.isna().sum().compute())
# print('Number of missing in fico_range_low: ', approved_data.fico_range_low.isna().sum().compute())
# print('Number of missing in fico_range_high: ', approved_data.fico_range_high.isna().sum().compute())
# print('Number of missing in grade: ', approved_data.grade.isna().sum().compute())
# print('Number of missing in home_ownership: ', approved_data.home_ownership.isna().sum().compute())
# print('Number of missing in initial_list_status: ', approved_data.initial_list_status.isna().sum().compute())
# print('Number of missing in installment: ', approved_data.installment.isna().sum().compute())
# print('Number of missing in int_rate: ', approved_data.int_rate.isna().sum().compute())
# print('Number of missing in issue_d: ', approved_data.issue_d.isna().sum().compute())
# print('Number of missing in loan_amnt: ', approved_data.loan_amnt.isna().sum().compute())
# print('Number of missing in open_acc: ', approved_data.open_acc.isna().sum().compute())
# print('Number of missing in pub_rec: ', approved_data.pub_rec.isna().sum().compute())
# print('Number of missing in pub_rec_bankruptcies: ', approved_data.pub_rec_bankruptcies.isna().sum().compute())
# print('Number of missing in purpose: ', approved_data.purpose.isna().sum().compute())
# print('Number of missing in sub_grade: ', approved_data.sub_grade.isna().sum().compute())
# print('Number of missing in term: ', approved_data.term.isna().sum().compute())
# print('Number of missing in verification_status: ', approved_data.verification_status.isna().sum().compute())
# print('Number of missing in zip_code: ', approved_data.zip_code.isna().sum().compute())
# print('Number of missing in loan_status: ', approved_data.loan_status.isna().sum().compute())


In [5]:
# print('Number of rows in the data: ', len(approved_data))

In [6]:
# Clean emp_length
approved_data.emp_length = approved_data.emp_length.replace(to_replace='< 1 year', value='0')
approved_data.emp_length = approved_data.emp_length.str.strip('<+ years')

In [7]:
mean_emp_length = np.floor(approved_data.emp_length.dropna().astype(int).mean())
approved_data.emp_length = approved_data.emp_length.fillna(mean_emp_length)

In [8]:
approved_data.emp_length = approved_data.emp_length.astype(int)

In [9]:
# Separate target from features
y = approved_data.loan_status
X = approved_data[['addr_state', 'annual_inc', 'application_type', 'disbursement_method', 'dti', 'earliest_cr_line', 'emp_length', 'fico_range_high', 'fico_range_low', 'grade',
'home_ownership', 'initial_list_status', 'installment', 'int_rate', 'issue_d', 'loan_amnt', 'open_acc', 'pub_rec', 'pub_rec_bankruptcies', 'purpose', 'sub_grade', 'term', 'verification_status']]

In [10]:
# Replace earliest_cr_line with number of days from earliest cr open to issue date
X.earliest_cr_line = X.earliest_cr_line.map_partitions(pd.to_datetime, meta=('earliest_cr_line', 'datetime64[ns]'))
X.issue_d = X.issue_d.map_partitions(pd.to_datetime, meta=('issue_d', 'datetime64[ns]'))
X['days_since_first_credit'] = (X.issue_d - X.earliest_cr_line).dt.days

In [11]:
# Drop earliest_cr_line and issue_d
X = X.drop(['earliest_cr_line', 'issue_d', 'grade'], axis=1)

In [12]:
approved_data.emp_length.value_counts().compute()

10    428296
5     157584
2     117971
0     104722
3     104288
1      85753
4      78078
6      60675
8      58718
7      57675
9      49323
Name: emp_length, dtype: int64

In [13]:
approved_data.annual_inc = approved_data.annual_inc[approved_data.annual_inc < 2e7]

In [14]:
ce = Categorizer(columns=['addr_state', 'application_type', 'disbursement_method', 'emp_length', 'home_ownership', 'initial_list_status', 'purpose', 'term', 'verification_status', 'sub_grade'])
X = ce.fit_transform(X)

In [15]:
de = DummyEncoder(columns=['addr_state', 'application_type', 'disbursement_method', 'emp_length', 'home_ownership', 'initial_list_status', 'purpose', 'term', 'verification_status', 'sub_grade'])
X = de.fit_transform(X)

In [16]:
le = LabelEncoder()
y = le.fit_transform(y)
y.compute()

array([1, 1, 1, ..., 1, 1, 1])

In [17]:
le.classes_.compute()

array(['Charged Off', 'Fully Paid'], dtype=object)

In [18]:
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [19]:
count_1 = y.sum() / len(y)
count_0 = 1 - count_1

In [20]:
lda = LinearDiscriminantAnalysis(priors=[0.5, 0.5])
cross_val_score(lda, X.compute(), y, cv=5)

array([0.80761424, 0.63395327, 0.65277016, 0.65348252, 0.64290374])

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X.compute(), y, test_size=0.2, shuffle=True)

/Users/darishsakeesing/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/__init__.py:181: PerformanceWarning: Slicing with an out-of-order index is generating 160126 times more chunks
  return array[key] if axis == 0 else array[:, key]
/Users/darishsakeesing/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/__init__.py:181: PerformanceWarning: Slicing with an out-of-order index is generating 40052 times more chunks
  return array[key] if axis == 0 else array[:, key]


In [22]:
lda1 = LinearDiscriminantAnalysis(priors=[0.5, 0.5])
lda1.fit(X_train, y_train)
# probs_positive_class = lda1.predict_proba(X_test)[:, 1]
# prediction = probs_positive_class > .9

LinearDiscriminantAnalysis(priors=[0.5, 0.5])

In [24]:
confusion_matrix(y_test, lda1.predict(X_test))

array([[ 31321,  18718],
       [ 70475, 140103]])

In [30]:
#Constructing priors list
priors = []
for x in range(0, 101, 1):
    priors.append([x/100, (100-x)/100])

In [36]:
# Constructing threshold list
threshold = np.linspace(start=0.01, stop=0.99, num = 99, endpoint=True)

In [45]:
def custom_scoring(estimator, X, y):
    cm = confusion_matrix(y, estimator.predict(X))
    score = cm[0, 1] + cm[1, 0]
    return score

In [49]:
results = []
X_train, X_test, y_train, y_test = train_test_split(X.compute(), y, test_size=0.2, shuffle=True)
for p in priors:
    lda = LinearDiscriminantAnalysis(priors=p)
    CV_scores = cross_val_score(estimator=lda, X = X_train, y = y_train, cv=3, n_jobs=-1, verbose=5, scoring=custom_scoring)
    results.append({'params': p, 'scores':CV_scores, 'mean_score': CV_scores.mean()})
    print(p, 'done')


/Users/darishsakeesing/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/__init__.py:181: PerformanceWarning: Slicing with an out-of-order index is generating 160161 times more chunks
  return array[key] if axis == 0 else array[:, key]
/Users/darishsakeesing/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/__init__.py:181: PerformanceWarning: Slicing with an out-of-order index is generating 40059 times more chunks
  return array[key] if axis == 0 else array[:, key]
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed: 10.8min remaining:    0.0s
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed: 10.8min finished
[0.0, 1.0] done
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed: 10.7min remaining:    0.0s
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed: 10.7min finished
[0.01, 0.99] done
[Parallel(n_jobs=-1)]: Usin

In [50]:
resultsDF = pd.DataFrame(results)
resultsDF

params                    scores     mean_score
0      [0.0, 1.0]     [66470, 66469, 66469]   66469.333333
1    [0.01, 0.99]     [66476, 66475, 66487]   66479.333333
2    [0.02, 0.98]     [66479, 66477, 66490]   66482.000000
3    [0.03, 0.97]     [66480, 66479, 66490]   66483.000000
4    [0.04, 0.96]     [66482, 66481, 66493]   66485.333333
5    [0.05, 0.95]     [66486, 66482, 66492]   66486.666667
6    [0.06, 0.94]     [66489, 66485, 66493]   66489.000000
7    [0.07, 0.93]     [66493, 66485, 66494]   66490.666667
8    [0.08, 0.92]     [66495, 66488, 66489]   66490.666667
9    [0.09, 0.91]     [66495, 66485, 66490]   66490.000000
10     [0.1, 0.9]     [66464, 66473, 66480]   66472.333333
11   [0.11, 0.89]     [66414, 66431, 66425]   66423.333333
12   [0.12, 0.88]     [66336, 66387, 66375]   66366.000000
13   [0.13, 0.87]     [66276, 66364, 66363]   66334.333333
14   [0.14, 0.86]     [66223, 66371, 66268]   66287.333333
15   [0.15, 0.85]     [66186, 66371, 66246]   66267.666667
16   [0.16, 0.84]     [66178, 66365, 66213]   66252.000000
17   [0.17, 0.83]     [66209, 66383, 66177]   66256.333333
18   [0.18, 0.82]     [66361, 66428, 66243]   66344.000000
19   [0.19, 0.81]     [66527, 66613, 66456]   66532.000000
20     [0.2, 0.8]     [66730, 66863, 66677]   66756.666667
21   [0.21, 0.79]     [67010, 67257, 66960]   67075.666667
22   [0.22, 0.78]     [67363, 67642, 67305]   67436.666667
23   [0.23, 0.77]     [67857, 68136, 67790]   67927.666667
24   [0.24, 0.76]     [68371, 68745, 68224]   68446.666667
25   [0.25, 0.75]     [69003, 69332, 68922]   69085.666667
26   [0.26, 0.74]     [69607, 70118, 69637]   69787.333333
27   [0.27, 0.73]     [70441, 70883, 70315]   70546.333333
28   [0.28, 0.72]     [71246, 71687, 71145]   71359.333333
29   [0.29, 0.71]     [72205, 72596, 71999]   72266.666667
30     [0.3, 0.7]     [73190, 73736, 72999]   73308.333333
31   [0.31, 0.69]     [74284, 74902, 74220]   74468.666667
32   [0.32, 0.68]     [75603, 76039, 75484]   75708.666667
33   [0.33, 0.67]     [76920, 77324, 76879]   77041.000000
34   [0.34, 0.66]     [78452, 78771, 78330]   78517.666667
35   [0.35, 0.65]     [80055, 80414, 79895]   80121.333333
36   [0.36, 0.64]     [81836, 82169, 81559]   81854.666667
37   [0.37, 0.63]     [83662, 83989, 83430]   83693.666667
38   [0.38, 0.62]     [85598, 86017, 85489]   85701.333333
39   [0.39, 0.61]     [87670, 88002, 87597]   87756.333333
40     [0.4, 0.6]     [89785, 90295, 89785]   89955.000000
41   [0.41, 0.59]     [92171, 92482, 92154]   92269.000000
42   [0.42, 0.58]     [94609, 95002, 94620]   94743.666667
43   [0.43, 0.57]     [97361, 97598, 97281]   97413.333333
44   [0.44, 0.56]  [100118, 100495, 100040]  100217.666667
45   [0.45, 0.55]  [103020, 103309, 102987]  103105.333333
46   [0.46, 0.54]  [106067, 106248, 106074]  106129.666667
47   [0.47, 0.53]  [109094, 109239, 109080]  109137.666667
48   [0.48, 0.52]  [112375, 112368, 112314]  112352.333333
49   [0.49, 0.51]  [115845, 115791, 115579]  115738.333333
50     [0.5, 0.5]  [119271, 119189, 119119]  119193.000000
51   [0.51, 0.49]  [122909, 122819, 122668]  122798.666667
52   [0.52, 0.48]  [126736, 126422, 126312]  126490.000000
53   [0.53, 0.47]  [130642, 130151, 130241]  130344.666667
54   [0.54, 0.46]  [134793, 134078, 134436]  134435.666667
55   [0.55, 0.45]  [139019, 138203, 138596]  138606.000000
56   [0.56, 0.44]  [143398, 142433, 142896]  142909.000000
57   [0.57, 0.43]  [147832, 146811, 147296]  147313.000000
58   [0.58, 0.42]  [152465, 151228, 151920]  151871.000000
59   [0.59, 0.41]  [157349, 155878, 156695]  156640.666667
60     [0.6, 0.4]  [162293, 160579, 161520]  161464.000000
61   [0.61, 0.39]  [167363, 165691, 166550]  166534.666667
62   [0.62, 0.38]  [172530, 170836, 171756]  171707.333333
63   [0.63, 0.37]  [177912, 176163, 177132]  177069.000000
64   [0.64, 0.36]  [183466, 181617, 182691]  182591.333333
65   [0.65, 0.35]  [189017, 187155, 188291]  188154.333333
66   [0.66, 0.34]  [194673, 193057, 193984]  193904.666667

In [51]:
resultsDF.to_csv('../data/results.csv')